repos:
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-cyclo
        args: [-over=15]
      - id: golangci-lint
      - id: go-critic
      - id: go-mod-tidy
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: master
    hooks:
      - id: my-cmd-repo
        name: go-test-doppler
        alias: go-test-doppler
        args: [ doppler run --command="go test ./tests" ]