version: "3"
services:
  serviceName-postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: serviceName-postgres
    volumes:
      - serviceName-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090

  # serviceName-app:
  #   image: serviceName:latest
  #   network_mode: bridge
  #   container_name: serviceName-app
  #   build: .
  #   expose:
  #     - 8880
  #   ports:
  #     - 8880:8880
  #   depends_on:
  #     - serviceName-postgres
  #   links:
  #     - serviceName-postgres
volumes:
  serviceName-data:
  prometheus_data: